# Generated by Django 2.2.4 on 2019-08-12 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_auto_20190811_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
